#!/bin/bash

connection_check_url="google.com"
api="https://api.tgju.online/v1/data/sana/json"
dollar_index=16
euro_index=17
data_backups_dir="$HOME/.local/share/erate"
dollar_price_file="$data_backups_dir/dollar.txt"
euro_price_file="$data_backups_dir/euro.txt"


check_internet_connection(){
        ping -q -w 5 -c 1 $connection_check_url > /dev/null 2>&1 && return 1 || return 0
}

get_price(){
	exchange=$1
	index=$2
	price_file=$3
	check_internet_connection
	if test $? -eq 1; then
		response=$(wget -q -O- $api)
		price=$(echo $response | jq ".sana | .data[$index].p")
		last_update=$(echo $response | jq ".sana | .data[$index].updated_at")
		show_info $exchange "$price" "$last_update" $price_file
	else
		echo Internet connection failed
		cat $price_file
	fi
}

get_dollar_price(){
	get_price "Dollar" $dollar_index $dollar_price_file
}

get_euro_price(){
	get_price "Euro" $euro_index $euro_price_file
}

show_info(){
	exchange=$1
	price=$2
	last_update=$3
	price_file=$4
        echo "$exchange: $price IRR" | tee $price_file
        echo "Last Update: $last_update" | tee -a $price_file
}

get_all_exchanges(){
	get_dollar_price
	get_euro_price
}

help(){
	echo 'COMMAND: erate [arguments]

whit no arguments, you can see the all rates.
argumetns:
	`dollar` or `d` for dollar price
	`euro` or `e` for euro price'
}

case $1 in
        dollar | d)
                get_dollar_price
                ;;
	euro | e)
		get_euro_price
                ;;
        --help | -h) 
                help
                ;;
        *)
                get_dollar_price
		;;
esac
