#!/bin/bash

connection_check_url="4.2.2.4"
api="https://api.tgju.online/v1/data/sana/json"
bitcoin_api="https://api.coindesk.com/v1/bpi/currentprice.json"
dollar_index=16
euro_index=17
data_backups_dir="$HOME/.local/share/erate"
dollar_price_file="$data_backups_dir/dollar.txt"
euro_price_file="$data_backups_dir/euro.txt"
btc_price_file="$data_backups_dir/btc.txt"


check_internet_connection(){
        ping -q -w 5 -c 1 $connection_check_url > /dev/null 2>&1 && echo 1 || echo 0
}

parse(){
	exchange=$1
	index=$2
	price=$(echo $response | jq ".sana | .data[$index].p")
	last_update=$(echo $response | jq ".sana | .data[$index].updated_at" | sed 's/\"//g')
	show_info $exchange "$price IRR" "$last_update" $price_file
}

get_price(){
	price_file=$3
	if test $internet_connection -eq 1; then
		response=$(wget -q -O- $api)
		parse $1 $2
	else
		echo Internet connection failed
		cat $price_file
	fi
}

get_dollar_price(){
	get_price "Dollar" $dollar_index $dollar_price_file
}

get_euro_price(){
	get_price "Euro" $euro_index $euro_price_file
}

get_btc_price(){
	if test $internet_connection -eq 1; then
		rate=$(wget -q -O- $bitcoin_api| jq ".bpi | .USD | .rate" | sed 's/\"//g')
		show_info "Bitcoin" "$rate USD" "$(date +"%F %H:%M:%S")" $btc_price_file
	else
		cat $btc_price_file
	fi	
}

show_info(){
	exchange=$1
	price=$2
	last_update=$3
	price_file=$4
        echo "$exchange: $price" | tee $price_file
        echo "Last Update: $last_update" | tee -a $price_file
}

get_all(){
	get_dollar_price
	get_euro_price
}

help(){
	echo 'COMMAND: erate [arguments]

whit no arguments, you can see the all rates.
argumetns:
	`dollar` or `d` for dollar price
	`euro` or `e` for euro price'
}

internet_connection=$(check_internet_connection)

case $1 in
        dollar | d)
                get_dollar_price
                ;;
	euro | e)
		get_euro_price
                ;;
	bitcoin | btc)
		get_btc_price
		;;
        --help | -h) 
                help
                ;;
        *)
		get_dollar_price
                # get_all
		;;
esac
